 -- TOTAL TRANSCRIPT --
 SELECT *
 FROM TRANSCRIPT;
 
 -- TRANSCRIPT FOR Student with ID = 4410 --
 SELECT *
 FROM TRANSCRIPT
 WHERE StudentID=4410;
 
 -- GRADES FOR ALL STUDENTS IN Course ID = 2355 --
SELECT *
FROM TRANSCRIPT
WHERE CourseID=2355;
 
-- SHOW TOTAL GRADES FOR THE ENTIRE SCHOOL --
SELECT COUNT(Grade), Grade
FROM TRANSCRIPT
GROUP BY Grade
ORDER BY Grade;

-- SHOW TOTAL GRADES FOR Student with ID = 4410 --
SELECT COUNT(Grade), Grade
FROM TRANSCRIPT
WHERE StudentID=4410
GROUP BY Grade
ORDER BY Grade;

-- SHOW TOTAL GRADES FOR COURSE WITH ID = 2355
SELECT COUNT(Grade), Grade
FROM TRANSCRIPT
WHERE CourseID=2355
GROUP BY Grade
ORDER BY Grade;
